name: Build app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.10.4
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv flask-api-test
          source flask-api-test/bin/activate

      - name: Install dependencies
        run: |
          make install
      
      - name: Test
        run: |
          make test